### ISSUE TITLE
STATE_ENCHANTED?

### ISSUE THREAD

**Issue by agb1** [RoxanneSHS/SandrahEET#1]
SandrahNPC/BAF/CVSanBeh.baf and SandrahNPC/ToB/CVSan25.baf reference STATE_ENCHANTED, but this is not in the original state.ids file nor added by Sandrah.  Is it added by another mod?

**Comment by RoxanneSHS** [comment]
There are some more like this, depending on your mods installed.
Since they do not prevent the install and do not cause problems in the game , I have kept them in some scripts for the moment. EET mod compliance is increased all the time and the mods to add these states and spells may yet be upgraded (I do not know which mod added what). My understanding is that Sandrah will use them and thus adapt itself to AI mods, but nothing will fail if the stuff is not there - other than to get a notification during install which you may ignore.
There is also the issue with an error saying Too few arguments for.... which is simply a wrong message as the script is correctly installed and working.

**Comment by RoxanneSHS** [comment]
Added it in Sandrah to avoid misleading reports - UNLESS (some mod adds it) 
Guess that is never wrong.
