### ISSUE TITLE
Question about 'Sandrah Illegal Add Ons'

### ISSUE THREAD

**Issue by wuxiangjinxing** [RoxanneSHS/SandrahEET#43]
It just occurred to me that there is a mod named as 'Sandrah Illegal Add Ons: v0.02' in my Weidu.log.  I downloaded the whole BWP integration package from a website so I have no idea what this mod is.  I roughly glanced at this mod and it seems to be a compatibility patch related to other companion mods, but obviously for very early version of Sandrah saga.  I did a google search and I found out that some other people also installed this mod but there was not much information.  (i.e. https://baldursextendedworld.com/Vanilla_Forums/discussion/732/where-to-find-sandra-in-bg2-bgeet)

Could you please maybe spend some time looking into this mod and see whether it shall be uninstalled?  I uploaded the mod in the following link:
https://drive.google.com/file/d/1KFPmxLdGbcC414XX74k7SaLUbbUCUwru/view?usp=sharing

Thank you very much.

**Comment by RoxanneSHS** [comment]
There is no need to uninstall this, much of it would have been skipped automatically by the installer because the respective NPC mods do not exist for EE. For those which exist there may be some crossmod added. This was taken out of the main mod because the authors of the other NPCs did not like it. 
The stuff is not maintained but it is coded in such a way that it does not harm anything.
