### ISSUE TITLE
Shauhana has inconsistent portraits

### ISSUE THREAD

**Issue by wuxiangjinxing** [RoxanneSHS/SandrahEET#55]
This might be trivial but Shauhana's large-size and small-size portraits are completely different.  She is a fighter in her small size-portrait while she looks more like a traveler in the other one.

Besides, when exploring the files I found out that there is another 'version' of Shauhana in game, named as 'CVshauQ.cre'.  Although I'm not sure whether this creature is really used or not, she also has two completely different portraits.  Besides, she cannot use her default items (the orc flaming sword, the bow and the book in her inventory).

**Comment by RoxanneSHS** [comment]
Part of that inconsistency is intentional, it should become evident from her story. Anyway, I made some modifications here recently including better portraits that better represent the story.
The ShauQ creature represents her after the Sharkta-Fai events - she becomes a plot person in later parts of the game...

The item issue is most likely some other mod that tweaks usability flags. You can just remove the usability flags with Near Infinity or EEKeeper, the items are still restricted to her by opcode 319.
Their codes are Shaubow.itm, Shaumai.itm and Shausw.itm (The books unusable is correct as you will find out during the quest, they are plot items and the fact that she cannot use them makes part of the story).

PS - if you need help with the items, just put them into a zip or the like and put them on dropbox or similar where I can download and change them. They are in the BG2EE/override folder.

**Comment by wuxiangjinxing** [comment]
Sorry to bother you again but I checked the usability of those items in both my override folder and your repository and they have exactly the same restriction.  
![1](https://user-images.githubusercontent.com/20956335/148704361-17827b4c-872a-4d35-98aa-8e71f464360b.jpg)
Could you please double-check those items in your game to see whether they can be used by Shau**Q**?  Thanks.

**Comment by RoxanneSHS** [comment]
I have updated the items yesterday to remove all the flags. The items are restricted to one NPC by association to the cre's script name via opcode 319.
CVShauq has a different script name but is not a joinable NPC anyway and only appears in scenes where she has no use for equipment (quest giving dialogues). She will later give a similar bow to her adopted son, who can join the party, but that is a different itm tuned for him.
