### ISSUE TITLE
Can't execute any commands in the console

### ISSUE THREAD

**Issue by Lichtenshtein** [RoxanneSHS/SandrahEET#61]
Hi. I apologize in advance that my issue is not about the mod itself.

I can't execute any commands in the console. i.e. i can write the commands themselves, but i cannot enter them - no reaction to pressing "enter".

Have no idea what to do. Have you ever come across anything like this?

**Comment by RoxanneSHS** [comment]
I have not heard of such an issue before?
Things to check:
In YourUserID/Documents/Baldur's Gate - Enhanced Edition Trilogy open the file baldur.lua  (Important: The game is NOT running in the background). Check that these lines exist, if not add them:

SetPrivateProfileString('Program Options','Debug Mode','1')
SetPrivateProfileString('Game Options','Cheats','1')

Note that in EE the Clua commands are no longer Clua but simply C: (e.g. C:CreateCreature("wolf01")

Are you using some exotic GUI mod or UITweaks component?

Otherwise I have no real clue what may cause it, other than some hardware/language configuration on your system.

**Comment by Lichtenshtein** [comment]
> Check that these lines exist

They do exist

> Note that in EE the Clua commands are no longer Clua but simply C: 

The problem is not just with commands but also with any plain text input - no response to pressing "enter"

> Are you using some exotic GUI mod or UITweaks component?

Yes i use these mods:
Dragonspear UI++ 22.01.2
Bubb's Spell Menu Extended 4.1
EEex v0.9.4-alpha
SCS difficulty component that interacts with UI

This morning I tried to install LeUI-SoD on top of my EET build, but the problem remained.

Maybe buggy EEex build for version 2.6? It causes some errors on game startup (but that didn't stop me from playing, the game works):

1) [string "M__MEFUN.lua"]:7674: attempt to call global 'EEex_AddActionHookOpcode' (a nil value)
2) [string "M_MESTR1.lua"]:33: attempt to call global 'EEex_FetchBCS' (a nil value)

**Comment by RoxanneSHS** [comment]
I have no experience with EEex and I would never use it in this context. The error text refers to some lua (GUI) stuff, but I do not know EEex enough to provide any details. None of the mods you mention is known for an error like your, so the main suspect would be EEex - but like I said, myself I avoid it by all means, so I cannot help you much.

**Comment by Lichtenshtein** [comment]
I remembered about the folder with Baldur's Gate - Enhanced Edition which then merged with BG II EE into EET. This is BG EE with the recommended mods from the trilogy build lists, no EEex or interface mods (otherwise the trilogy is not installed). So, it also has the described problem.

If the problem is really related to "hardware/language configuration on your system", i don't understand what the problem could be at all.

**Comment by RoxanneSHS** [comment]
Mods do not interfere with those settings. Cheat/console commands enabling is done locally by the user. You can also check through the game configuration screens that come up in game itself to see if you find anything unusual.
Also take a look at your language settings in game.
Otherwise this is not a problem of mods at all since they do not deal with this.

**Comment by Lichtenshtein** [comment]
Huh. I CAN write with the Windows on-screen keyboard. Sounds like it's definitely system/hardware related. I'll look into it. Or will enter commands from the on-screen keyboard if nothing works, lol.

Thank you for your patience.
