### ISSUE TITLE
Getting an error on installation

### ISSUE THREAD

**Issue by LazyDunmer** [RoxanneSHS/SandrahEET#72]
When I attempt to install I am getting this error message for Sandrah NPC Creatures & Items component 5 version 2.07: 

ERROR: cannot convert %CVMystra% or %%CVMystra%% to an integer
ERROR: [SandrahNPC\CRE/Sandrah.cre] -> [override\Sandrah.cre] Patching Failed (COPY) (Not_found)
ERROR: Not_found
SandrahNPC Creatures and Items (Sandrah Saga I - Sandrah Appears) was not installed due to errors.

Is there something I am not doing or need to do?

**Comment by RoxanneSHS** [comment]
This error usually appears when you either have an already corrupted installation or you try to install mods in a protected part of your computer (e.g. steamapps or programs or games). Another possibility is that the game had been modded before and old remains are blocking files.
You can try and uninstall manually the parts of Sandrah that are already installed and then do her again all over. Otherwise, there are too many possibilities of what went wrong before.

**Comment by LazyDunmer** [comment]
Thanks for responding so quickly. I can rule out the second possibility at least as well as the third as its a clean install. Ill try re-downloading thanks.

Just a couple of quick questions if I may. If I decide to skip this component a)will it break the rest of the mod? and b) will I miss out on much content?

**Comment by RoxanneSHS** [comment]
The mod will not work at all. Components of the mod are building on each other, they are not options.

**Comment by LazyDunmer** [comment]
ok thanks
