### ISSUE TITLE
The premature end of the romance with Branwen

### ISSUE THREAD

**Issue by SergGrey** [RoxanneSHS/SandrahEET#80]
Hello, please advise. Started a romance Branwen from the BG1NPC mod and at some point in the city begins a dialogue that she can't stand the change and leaves. Is there any way to keep her? Checked the code, it seems like if you leave Sandra waiting in the temple and advance the romance, the condition for triggering the break won't work, but I guess it's a crutch. Since in the code I saw a continuation in BG2

**Comment by RoxanneSHS** [comment]
It is not premature end. The romance from BG1NPC mod gets a break when Branwen needs to sort out her relationship between the lover and her god Tempus. It is normal. Sandrah does not change anything, just comments on it.
BG2 Branwen is complete other mod - I do not know about that one because I never use it.
Branwen in later Sandrah mod (Return to Faerun) is again something different, there you meet Branwen 10 years after the earlier events and former mods have no impact on that.

There is a pdf-file in the BG1NPC mod folder with details about the BG1 romances.

**Comment by SergGrey** [comment]
Sorry, I didn't expect the romance in the original fashion to end this way. The pdf file describes 4 more LTs, and with Sandra, Branwen leaves the group and can't be found anywhere. In BG1NPC she sort of can be either left in the group or chased away in this situation (and in the original the condition for this scene requires chapter 7, and here I got it at chapter 3 xD). And about BG2, I wasn't writing about BG2 Branwen, but about the fact that Sandra's BG2 files have a romance ending check

**Comment by RoxanneSHS** [comment]
If you look at the conditions for Branwen LT, you see that LT20 is the last one. The four that are quoted afterwards are conditional talks out of sequence e.g. when at Candlekeep or Undercity.
