### ISSUE TITLE
Question: what are the mods relating to Mystra being endangered?

### ISSUE THREAD

**Issue by wuxiangjinxing** [RoxanneSHS/SandrahEET#84]
In the Sandrah saga manual it says:
_At least one of the mods relating to Mystra being endangered is required to complete 
Sandrah's SoA part and let her follow you into ToB - either Tales of Anegh or the third 
part of Grey Clan, which comes with Sandrah._

Could you specify which mods are you refering to? Thanks.

**Comment by RoxanneSHS** [comment]
It is either the final episode of Tales of Anegh or the TDDz - Onset of the Darkest Day or the Sandrah Grey Clan pt3 (inside Sandrah mod itself. 
The information is partly outdated because in the latest versions of Sandrah that 3. option is always included and also it is no longer necessary to finish everything until the ToB transition (because in EET now you can always easily go back to SoA areas once you can access the worldmap outside Saradush.
